language: node_js
node_js:
  - '6'
install:
  - npm install
script:
  - npm run unit
before_deploy:
  - npm run build
deploy:
  skip_cleanup: true
  provider: surge
  project: ./dist/
  domain: foreign-exchange-prototype.surge.sh
  on:
    branch: master
